baseURL = 'https://zh.neweeks.com/' # 这是你的中文博客域名
languageCode = 'zh-cn' # 设定语言代码为中文简体
title = '周周新' # 你的中文博客标题
theme = 'lightbi-hugo' # 指定使用的主题
enableGitInfo = true # 建议开启，因为主题会用到，但如果Cloudflare Pages有问题再禁用
defaultContentLanguage = "zh" # 设定默认内容语言为中文
defaultContentLanguageInSubdir = false

[params]
  selfHosted = true # 根据主题文档，这个参数可能是必须的

[menu]
  [[menu.main]]
    name = "首页" # 菜单项名称改为中文
    url = "/"
    weight = 1
  [[menu.main]]
    name = "文章" # 菜单项名称改为中文
    url = "/post/"
    weight = 2
  [[menu.main]]
    name = "关于" # 菜单项名称改为中文
    url = "/about/"
    weight = 3